#!/bin/bash
#SBATCH -N 2
#SBATCH -C knl
#SBATCH -q regular
#SBATCH --mail-user=tlhuang@bu.edu
#SBATCH --mail-type=ALL
#SBATCH -t 00:30:00
#SBATCH --array=1-100
#SBATCH -o interstitial_C3_config%a/slurm-%A_%a.out

#OpenMP settings:
export OMP_NUM_THREADS=4
export OMP_PLACES=threads
export OMP_PROC_BIND=true

module load espresso/6.5

srun -n 34 -c 16 --cpu_bind=cores pw.x -in interstitial_C3_config${SLURM_ARRAY_TASK_ID}/Li_pw.in
